col_bg: &col_bg 0B151DFF
col_fg: &col_fg C5C8C6FF
col_active: &col_active AC8AACFF
col_empty: &col_empty 404B66FF
col_occupied: &col_occupied C6D2EDFF
col_red: &col_red BD6B64FF
col_yellow: &col_yellow C7B079FF
col_blue: &col_blue 6A9FB8FF
col_magenta: &col_magenta A6729FFF
col_green: &col_green 5CB574FF

main_font: &main_font Iosevka Nerd Font:style=Regular:pixelsize=14
title_font: &title_font Iosevka Nerd Font:style=Bold:pixelsize=14
icon_font: &icon_font Iosevka Nerd Font:style=Bold:pixelsize=14
std_underline: &std_underline {underline: { size: 3, color: *col_active}}
bar:
  monitor: DP-2
  height: 35
  location: top
  layer: bottom
  spacing: 5
  background: *col_bg
  foreground: *col_fg
  margin: 7

  font: *main_font
  
  left:
     - label:
         content:
           string:
             text: "  "
             font: *icon_font
             foreground: *col_occupied
     - i3:
        sort: ascending
        anchors:
          - string: &i3_common {margin: 5, on-click: "swaymsg --quiet workspace {name}"}
          - string: &default {<<: *i3_common, text: " {name} ", foreground: *col_fg}
          - focused: &focused
              deco: {stack: [ *std_underline]}
          - invisible: &invisible {foreground: ffffff55}
          - urgent: &urgent
              foreground: 000000ff
              deco: {stack: [background: {color: bc2b3fff}, <<: *std_underline]}
          #- map: &i3_mode
          #    tag: mode
          #    default:
          #      - string:
          #          margin: 5
          #          text: "{mode}"
          #          deco: {background: {color: cc421dff}}
          #      - empty: {right-margin: 7}
          #    values:
          #      default: {empty: {}}
        content:
          "":
            map:
              conditions:
                state == focused:   {string: {<<: [*default, *focused]}}
                state == unfocused: {string: {<<: *default}}
                state == invisible: {string: {<<: *default, foreground: *col_occupied}}
                state == urgent:    {string: {<<: [*default, *urgent]}}
  right:
    - script:
        path: /home/mrkcee/.config/common_scripts/bar/audio.zsh
        content:
          map:
            on-click: "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
            conditions:
              muted:
                string:
                  margin: 3
                  text: " "
                  font: *title_font
              ~muted:
                string:
                  margin: 3
                  text: " {volume}%"
                  font: *title_font

    - network:
        name: wlp38s0
        poll-interval: 15
        content:
          map:
            on-click: "footclient --title=nmtui -e nmtui"
            conditions:
              ~carrier:
                string:
                  margin: 3
                  text: "󰤮 "
                  font: *icon_font
                  foreground: *col_red
              carrier:
                string:
                  margin: 3
                  text: " "
                  font: *icon_font    
    - clock:
        time-format: "%I:%M %p"
        date-format: "%B %d"
        content:
          string:
            margin: 3
            text: "   {date}    {time}"
            font: *title_font
            foreground: *col_occupied
    - label:
        content:
          string:
            on-click: "footclient --title=powermenu -e /home/mrkcee/.config/common_scripts/powermenu.zsh"
            text: " "
            font: *icon_font
            foreground: *col_red
            margin: 3
