#!/bin/zsh -e

# wallpaper
wbg $HOME/Downloads/aisberg-voda-art-ostrov-led-arktika-krasota.jpg

# audio
pkill -x pipewire > /dev/null || pipewire &
pkill -x pipewire-pulse > /dev/null || pipewire-pulse &

sleep 1

# status bar
pkill -x waybar > /dev/null || waybar &

# notification
exec mako
